fieldLayouts:
  bfa48288-8ec7-4f30-9cad-64c1bb8169b3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: homeBioImages
hasUrls: true
name: 'Home Bio Images'
settings:
  path: '@webroot/src/img/homeBioImages'
sortOrder: 4
type: craft\volumes\Local
url: '@web/src/img/homeBioImages'
