fieldLayouts:
  ff36f883-93dd-4d43-a373-28a3d128c6d3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: places
hasUrls: true
name: Places
settings:
  path: '@webroot/src/img/places'
sortOrder: 2
type: craft\volumes\Local
url: '@web/src/img/places'
