contentColumnType: text
fieldGroup: eb5bd566-3f23-4b68-9338-3d338db1bc94
handle: bioHeadline
instructions: 'The headline for the Bio section'
name: 'Bio Headline'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
