enableVersioning: true
handle: places
name: 'Incredible Places'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6c05cbc8-5baf-424c-8db8-bafbf36a85e6:
    enabledByDefault: true
    hasUrls: true
    template: places/_entry
    uriFormat: 'places/{slug}'
type: channel
